name: sliiders
channels:
  - conda-forge
dependencies:
  - beautifulsoup4=4.12.2
  - cartopy=0.22.0
  - contextily=1.4.0
  - dask-geopandas=0.3.1
  - distributed=2023.8.1
  - fsspec=2023.9.0
  - jupyterlab=4.0.5
  - matplotlib=3.8.0
  - networkx=3.1
  - numba=0.57.1
  - numpy=1.24.4
  - numpy_groupies=0.9.22
  - pandas=2.1.0
  - pandas-datareader=0.10.0
  - pint=0.22
  - pygeos=0.14
  - pyinterp=2023.10.1
  - pypdf2=2.11.1
  - pyreadr=0.4.9
  - python=3.10.12
  - regionmask=0.11.0
  - requests=2.31.0
  - rioxarray=0.15.0
  - scikit-learn=1.3.0
  - scipy=1.11.2
  - shapely=2.0.1
  - statsmodels=0.14.0
  - tqdm=4.66.1
  - xarray=2023.8.0
  - xesmf=0.8.1
  - zarr=2.16.1
