name: sliiders
channels:
  - conda-forge
dependencies:
  - beautifulsoup4=4.12.3
  - cartopy=0.22.0
  - contextily=1.6.0
  - dask-geopandas=0.3.1
  - distributed=2024.3.1
  - fsspec=2024.3.1
  - jupyterlab=4.1.5
  - matplotlib=3.8.3
  - networkx=3.2.1
  - numba=0.59.0
  - numpy=1.26.4
  - numpy_groupies=0.10.2
  - pandas=2.2.1
  - pandas-datareader=0.10.0
  - pint=0.23
  - pyinterp=2024.3.0
  - pypdf2=2.11.1
  - pyreadr=0.5.0
  - python=3.12.2
  - regionmask=0.12.1
  - requests=2.31.0
  - rioxarray=0.15.1
  - scikit-learn=1.4.1.post1
  - scipy=1.12.0
  - shapely=2.0.3
  - statsmodels=0.14.1
  - tqdm=4.66.2
  - xarray=2024.2.0
  - xesmf=0.8.4
  - zarr=2.17.1
